Repository AY2425S2-CS2103T-T13-4/tp, pull requests merged in 2025-03, with the labels that each got.

#60 Add zimeng's photo
  docs/images/jiangsuwangjing.png
Labels: type.Task

#61 Update about us for zimeng
  docs/AboutUs.md
Labels: type.Task

#71 Update README
  README.md
Labels: type.Task

#78 Branch add student
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/Subject.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Story, type.Task

#81 Implement delete student command
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
Labels: type.Task

#103 Minor change in error handling when adding student
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/model/student/Email.java
  src/main/java/seedu/address/model/student/Phone.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Task

#111 Add tests for AddStudentCommand and Subject
  src/main/java/seedu/address/model/student/Subject.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/model/student/SubjectTest.java
Labels: type.Task

#144 Implement edit student command
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditStudentCommandParser.java
Labels: type.Task

#145 Implement delete assignment
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/model/assignment/UniqueAssignmentList.java
  src/main/java/seedu/address/model/student/Student.java
Labels: type.Task

#146 Update edit student and delete assignment sections
  docs/UserGuide.md
Labels: type.Task

#155 Fix bug in delete assignment
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/UniqueAssignmentList.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: type.Bug

#164 Replace unique subject list in UML
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task

#192 Fix error message for DeleteStudentCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
Labels: alpha-bug

#195 Fix error message for empty lesson for delete_lesson
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/test/java/seedu/address/logic/commands/DeleteLessonCommandTest.java
Labels: alpha-bug

#201 Fix display message for Lesson subject
  src/main/java/seedu/address/logic/Messages.java
Labels: alpha-bug

#204 Update UG to remove repeated features
  docs/UserGuide.md
Labels: alpha-bug
